# HTTP Server
server:  
  port: 9999   # HTTP port

spring:  
  application:    
    name: tracking
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}    
    
logging:
  file: logs/${spring.application.name}.log
  pattern:
    console: "%d %-5level %logger{5} %M : %msg%n"
    file: "%d %-5level %logger{5} %M : %msg%n"
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.docomo.fraudwall: 'INFO' 
    org.springframework.kafka: 'INFO'
          

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

msg:
  partnerNameNoExist: Error to generating session, then partner name not exist. 
  ssesionSuccess: Session generated Successfully
  sessionOrPartnerNoExist: Session/partner Name not exist
  tokenOrPartnerNoExist: Session/partner Name not exist
  tokenSuccess: Session generated Successfully
  sessionBadPartnerName: There are some partned with the same name
  msgDataInvalid: Date format not valid

---
spring:
  profiles: local
  data:
    mongodb:            
      host: localhost
      port: 27017
      

kafka:   
  bootstrap-servers: localhost:9092
  
#mid1-db145hdflcatpp-1.hd.docomodigital.com:9092,mid1-db145hdflcatpp-2.hd.docomodigital.com:9092,mid1-db145hdflcatpp-3.hd.docomodigital.com:9092,mid1-db248hdflddsfwpp-1:9092
  port: 9092
  topic: HDP_FW_TRACK        
  #keyTab: #C:\\borrar\\hdp_b2bp_app.keytab
  #keyTabUser: hdp_b2bp_app@AD.DOCOMODIGITAL.COM  
  #security: PLAINTEXT
  #PLAINTEXT SASL_PLAINTEXT
  #useKeyTab: fasle
  #storeKey: false
  #clientIdConfig: fraudwall-spring
  security: PLAINTEXT
  useKeyTab: false
  storeKey: false
  clientIdConfig: fraudwall-spring
  keyTabPlace: C:\\Docomo\\proyectos\\fraudwall\\hdp_b2bp_app.keytab
  keyTabUser: hdp_b2bp_app@AD.DOCOMODIGITAL.COM  
# properties:
#    protocol: SASL_SSL

#kafka:
#  bootstrap-servers: localhost
#  port: ${PORT_KAFKA_PRODUCER}
#  topic: HDP_FW_TRACK
  
--- 
spring:
  profiles: openshift
  data:
    mongodb:            
      host: mongo
      port: 27017
      database: fraudwall
      username: alf
      password: alf
#  bootstrap-servers: mid1-db248hdflddsfwpp-1:2181

#mid1-db145hdflcatpp-1.hd.docomodigital.com:9092,mid1-db145hdflcatpp-2.hd.docomodigital.com:9092,mid1-db145hdflcatpp-3.hd.docomodigital.com:9092,mid1-db248hdflddsfwpp-1:9092
#  port: 9092
#  topic: HDP_FW_TRACK        
#  keyTab: #C:\\borrar\\hdp_b2bp_app.keytab
#  keyTabUser: #hdp_b2bp_app@AD.DOCOMODIGITAL.COM
#  security: PLAINTEXT://:9092
#  useKeyTab: false
#  storeKey: false
#  clientIdConfig: fraudwall-spring
kafka:   
  bootstrap-servers: 192.168.127.142:9092,192.168.127.143:9092,192.168.127.144:9092 
#mid1-db248hdflddsfwpp-1:9092,mid1-db248hdflddsfwpp-2:9092, mid1-db248hdflddsfwpp-3:9092
  port: 9092
  topic: HDP_FW_TRACK        
  #keyTab: #C:\\borrar\\hdp_b2bp_app.keytab
  #keyTabUser: hdp_b2bp_app@AD.DOCOMODIGITAL.COM
  security: SASL_SSL
  #security: PLAINTEXT
  useKeyTab: true
  storeKey: true
  clientIdConfig: test
  keyTabPlace: /app/hdp_b2bp_app.keytab
  keyTabUser: hdp_b2bp_app@AD.DOCOMODIGITAL.COM
  
call:
  partner: 
    protocol: http
    hostname: partner
    port: 2222
    resources: partner
    operation: getByName

---
spring:
  profiles: docker
  data:
    mongodb:
     host: mongodb	
      #host: mongodb
      #port: 27017
      #database: fraudwall
    #mongodb:            
    #  host: mid1-s076stgmng-1.buongiorno.com
     # port: 27017
      #database: cat
      #user: cat_user
      #password: mf15mdj	  
#kafka:
  #bootstrap-servers: kafka
  #topic: HDP_FW_TRACK
#  port: ${PORT_KAFKA_PRODUCER}
  
kafka:   
  bootstrap-servers: kafka:9092 
  port: 9092
  topic: HDP_FW_TRACK        
  #keyTab: #C:\\borrar\\hdp_b2bp_app.keytab
  #keyTabUser: hdp_b2bp_app@AD.DOCOMODIGITAL.COM
  security: #PLAINTEXT://:9092
  useKeyTab: false
  storeKey: false
  clientIdConfig: fraudwall-spring    