# HTTP Server
server:  
  port: 1111   # HTTP port

# Discovery Server Access
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:  
  application:
    name: tracking

prueba:
  nombre: ALFONSO

  
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true	  