# HTTP Server
server:  
  port: 1111   # HTTP port

#spring:  
  #application:
    #name: tracking
  #data:
    #mongodb:            
      #host: mongodb
      #port: 27017
      #database: fraudwall  
#      username: alf
#      password: alf  

spring:  
  application:
    name: tracking
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fraudwall            
 
logging:
  file: logs/${spring.application.name}.log
  pattern:
    console: "%d %-5level %logger{5} %M : %msg%n"
    file: "%d %-5level %logger{5} %M : %msg%n"
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.docomo.fraudwall: 'DEBUG' 
          
prueba:
  nombre: ALFONSO
  apellidos: HERREROS

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
    
# HTTP Server
#server:  
#  port: 8080   # HTTP port

# Discovery Server Access
#eureka:  
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#spring:  
#  application:
#    name: tracking
#
#prueba:
#  nombre: ALFONSO
#  apellidos: HERREROS


#mongodb
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: app1

#  
#endpoints:
#  health:
#    sensitive: false
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true	  