# HTTP Server
server:  
  port: 1111   # HTTP port

#spring:  
  #application:
    #name: tracking
  #data:
    #mongodb:            
      #host: mongodb
      #port: 27017
      #database: fraudwall  
#      username: alf
#      password: alf  

spring:  
  application:
    name: tracking
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fraudwall
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

#  cloud:
#    stream:
#      kafka:
#        sleuth:
#          enabled: true
#          sampler.percentage: '1.0'
#        binder:
#          zkNodes: kafka
#          brokers: kafka
#          defaultZkPort: 2181
#          defaultBrokerPort: 9092
#          autoAddPartitions: true
#          headers:
#            - spanId
#            - spanSampled
#            - spanProcessId
#            - spanParentSpanId
#            - spanTraceId
#            - spanName
#            - messageSent


			
logging:
  file: logs/${spring.application.name}.log
  pattern:
    console: "%d %-5level %logger{5} %M : %msg%n"
    file: "%d %-5level %logger{5} %M : %msg%n"
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.docomo.fraudwall: 'INFO' 
    org.springframework.kafka: 'INFO'
          
prueba:
  nombre: ALFONSO
  apellidos: HERREROS

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
    

## HTTP Server
# HTTP Server
server:  
  port: 8080   # HTTP port

spring:  
  application:
    name: tracking
  data:
    mongodb:            
      host: mongodb
      port: 27017
      database: fraudwall  
      username: alf
      password: alf  
          
 
logging:
  file: logs/${spring.application.name}.log
  pattern:
    console: "%d %-5level %logger{5} %M : %msg%n"
    file: "%d %-5level %logger{5} %M : %msg%n"
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.atsistemas.omega: 'DEBUG' 
          
prueba:
  nombre: ALFONSO
  apellidos: HERREROS

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
    